# Generated by Django 3.2.4 on 2021-09-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_secrets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secrets',
            old_name='email',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='secrets',
            old_name='pas',
            new_name='password',
        ),
        migrations.AddField(
            model_name='secrets',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
